<?php

use PHPUnit\Framework\TestCase;

require_once FCPATH . 'app/models/Session.php';

/**
 * Session::validateCSRFToken() die()s on mismatch rather than returning
 * false, which can't be exercised here without killing the test process -
 * this covers the success path (a token generated by the same session
 * validates), which is what the CSRF-guarded controllers actually rely on.
 */
class CsrfTest extends TestCase
{
    protected function tearDown(): void
    {
        if (session_status() === PHP_SESSION_ACTIVE) {
            session_destroy();
        }
        $_SESSION = [];
    }

    public function test_generated_token_validates_successfully(): void
    {
        $session = new \Core\Session();
        $token = $session->generateCSRFToken();

        $this->assertIsString($token);
        $this->assertNotSame('', $token);
        $this->assertTrue($session->validateCSRFToken($token));
    }

    public function test_same_token_returned_on_repeated_calls(): void
    {
        $session = new \Core\Session();
        $first = $session->generateCSRFToken();
        $second = $session->generateCSRFToken();

        $this->assertSame($first, $second);
    }
}
